// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: example_items.sql

package exampledb

import (
	"context"
)

const createExampleItem = `-- name: CreateExampleItem :one
INSERT INTO example_items (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateExampleItem(ctx context.Context, name string) (ExampleItem, error) {
	row := q.db.QueryRow(ctx, createExampleItem, name)
	var i ExampleItem
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteExampleItem = `-- name: DeleteExampleItem :exec
DELETE FROM example_items
WHERE id = $1
`

func (q *Queries) DeleteExampleItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteExampleItem, id)
	return err
}

const getExampleItem = `-- name: GetExampleItem :one
SELECT id, name, created_at
FROM example_items
WHERE id = $1
`

func (q *Queries) GetExampleItem(ctx context.Context, id int64) (ExampleItem, error) {
	row := q.db.QueryRow(ctx, getExampleItem, id)
	var i ExampleItem
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listExampleItems = `-- name: ListExampleItems :many
SELECT id, name, created_at
FROM example_items
ORDER BY id
LIMIT 100
`

func (q *Queries) ListExampleItems(ctx context.Context) ([]ExampleItem, error) {
	rows, err := q.db.Query(ctx, listExampleItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExampleItem
	for rows.Next() {
		var i ExampleItem
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
