// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package exampledb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExampleItem struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
